### testar a raiz do projeto
http://localhost:5244

// CRUD da classe PokemonWiki
### cadastrar pokemon
POST http://localhost:5244/api/pokemon_wiki/cadastrar
Content-Type: application/json

{
    "nome": "Sylveon",
    "tipoId": 1,
    "descricao": "Muito kawaizinha",
    "evoluiPara": [],
    "preEvolucoes": ["Evee"]
}

### listar todos os pokemons
GET http://localhost:5244/api/pokemon_wiki/listar

### buscar um pokemon pelo nome
GET http://localhost:5244/api/pokemon_wiki/buscar/Sylveon

### deletar um pokemon pelo nome
DELETE http://localhost:5244/api/pokemon_wiki/deletar/Sylveon

### alterar informações do pokemon
PUT http://localhost:5244/api/pokemon_wiki/alterar/Sylveon
Content-Type: application/json

{
    "nome": "Sylveon3",
    "tipoId": 2,
    "descricao": "Muito kawai.",
    "evoluiPara": [],
    "preEvolucoes": ["Evee"]
}

// CRUD da classe SeusPokemons
### cadastrar pokemon
POST http://localhost:5244/api/seu_pokemon/cadastrar
Content-Type: application/json

{
    "nome": "Flareon",
    "tipoId": 2,
    "pc": 1700
}

### listar todos os pokemons
GET http://localhost:5244/api/seu_pokemon/listar

### buscar um pokemon pelo id
GET http://localhost:5244/api/seu_pokemon/buscar/1

### deletar um pokemon pelo id
DELETE http://localhost:5244/api/seu_pokemon/deletar/1

### alterar informações do pokemon
PUT http://localhost:5244/api/seu_pokemon/alterar/2
Content-Type: application/json

{
    "nome": "Magmar2",
    "tipos": 1,
    "pc": 1800
}

// CRUD da classe Batalha
### cadastrar uma batalha
POST http://localhost:5244/api/batalha/cadastrar/2/3
Content-Type: application/json

{
    "titulo": "teste"
}

### listar todas as batalhas
GET http://localhost:5244/api/batalha/listar

### buscar uma batalha pelo id
GET http://localhost:5244/api/batalha/buscar/1

### deletar uma batalha pelo id
DELETE http://localhost:5244/api/batalha/deletar/1

// tipos
### listar tipos
GET http://localhost:5244/api/tipo/listar

### cadastrar tipo
POST http://localhost:5244/api/tipo/cadastrar
Content-Type: application/json

{
    "nome" : "Água"
}