// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations.BatalhaData
{
    [DbContext(typeof(BatalhaDataContext))]
    partial class BatalhaDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("API.Models.Batalha", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataBatalha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Batalhas");
                });

            modelBuilder.Entity("API.Models.BatalhaPokemon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatalhaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePokemon1")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePokemon2")
                        .HasColumnType("TEXT");

                    b.Property<int>("PcPokemon1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PcPokemon2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BatalhaId");

                    b.ToTable("BatalhaPokemons");
                });

            modelBuilder.Entity("API.Models.BatalhaPokemon", b =>
                {
                    b.HasOne("API.Models.Batalha", "Batalha")
                        .WithMany("PokemonsNaBatalha")
                        .HasForeignKey("BatalhaId");

                    b.Navigation("Batalha");
                });

            modelBuilder.Entity("API.Models.Batalha", b =>
                {
                    b.Navigation("PokemonsNaBatalha");
                });
#pragma warning restore 612, 618
        }
    }
}
