// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241116195253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Models.Batalha", b =>
                {
                    b.Property<int>("BatalhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataBatalha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pokemon1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pokemon2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vencedor")
                        .HasColumnType("TEXT");

                    b.HasKey("BatalhaId");

                    b.HasIndex("Pokemon1Id");

                    b.HasIndex("Pokemon2Id");

                    b.ToTable("Batalhas");
                });

            modelBuilder.Entity("API.Models.PokemonWiki", b =>
                {
                    b.Property<int>("PokemonWikiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EvoluiPara")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PreEvolucoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tipos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PokemonWikiId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PokemonsWiki");
                });

            modelBuilder.Entity("API.Models.SeusPokemons", b =>
                {
                    b.Property<int>("SeusPokemonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PC")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tipos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeusPokemonsId");

                    b.ToTable("SeusPokemons");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API.Models.Batalha", b =>
                {
                    b.HasOne("API.Models.SeusPokemons", "Pokemon1")
                        .WithMany()
                        .HasForeignKey("Pokemon1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.SeusPokemons", "Pokemon2")
                        .WithMany()
                        .HasForeignKey("Pokemon2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon1");

                    b.Navigation("Pokemon2");
                });
#pragma warning restore 612, 618
        }
    }
}
